SprintPlayer.java
Minor changes to workers so that they find a spot to make factories and first factory built by initial workers. Knights now attack and try to go to a attackLoc.
=> Update with attacking mechanisms for knights

SprintPlayer.java
Very important update: moveToLoc now goes around obstacles and rockets are now being produced. The rockets loads 8 knights and then takes off. The rocket then lands and unloads the knights onto Mars.
=> Updated movement and implemented rockets

SprintPlayer.java
This is the Sprint Tournament player that we will be submitting. It now checks for karbonite and harvests it.
=> Sprint Tournament Player

SprintPlayer.java
Fixed rocket so that it checks if land location is on map.
=> Fixed Rocket error

SprintPlayer.java
We send rockets to mars more often and got rid of unit production inhibitions and changed research queue to add rangers and mages. Fixed a bunch of other stuff as well
=> Fixed rocket sending

SprintPlayer.java
Made it match the filename
No longer causes compile errors when running through the Battlecode launcher
=> Fix SprintPlayer classname

Player.java
Movement: Now we are using bfs for moving to swarmLoc and for workers getting to rockets
Rockets: Rockets are actually being built reliably and units will not move to the buildLoc of a rocket
Swarming: Troops will not go to swarmLoc until troopSize is > 15
=> Updated movement, rockets, and added swarming

Player.java
Previously, workers would not move at all on Mars. The problem was that the workers were trying to replicated but could not because findOpenAdjacentSpot was only using earthMap. Now it uses thisMap which is a new static variable.
=> Fixed workers on Mars

Player.java
Removed rangerMoveToAttack(), added retreat to attack range edge code
=> Update ranged unit code

Player.java
Movement with BFS is actually implemented and Ben's ranged unit retreat code is in as well.
=> Updated movement and ranged unit code

Player.java
Workers not being stalled if can't replicate a worker
=> Worker update

Player.java
Knights now get javelin and use it
=> Updated knights

Player.java
=> Fixed ranged unit idle turns

Player.java
Workers moving to build factories now use BFS to move to buildLoc.
=> Factory building now uses BFS

Player.java
Units only go to rockets after the rocket is finished being built
=> Fixed unit movement to rocket

Player.java
Changed ratio so that there are more karbonite collecting workers
=> More karbonite collecting workers

Player.java
Production is now based on size of map so that strategy is more adaptive. In addition, research is also changed to adapt and favor either knight of ranger.
=> Changed production in early game

Player.java
Workers now collect karbonite that is adjacent and also use bfs to go to karbonite locations.
=> Update Worker Movement

Player.java
Bouncing now stays out of buildLoc and # of factories and minimum swarm size dependent on map size.
=> Updated workers and swarming

Player.java
Healers are now properly implemented and movement now is restricted while building up forces then unleashes them.
=> Major update to healers and movement

Player.java
Healers have a different safeDistance when bounceMoving. Also, other stuff like unitToRocket fixed
=> Updated Miscellaneous

Player.java
Workers use bfs karbonite harvesting again. Using a localized bfs search to save time.
=> Updated BFS Karbonite harvesting

Player.java
Building of rockets is now dependent on map size
=> Added adjustable rocket time

Player.java
Reverts androidmage/Pie-Baking-Contest#35
=> Revert "Added adjustable rocket time"

Player.java
=> Minor speed performance update

Player.java
Swarming now slows down production at same time as before but builds up troops by 5 more. Karbonite collection updates more in the beginning and less after the early game. Also, only use BFS for first 300 rounds.
=> Updated swarming and karbonite collection

Player.java
=> Give rangers ability to snipe factories if far from enemies

Player.java
Integrated Leon's code for rocket waiting and finding a good time to send rockets. Updated with Ben's ranger sniping code but won't be using sniping because it takes 200 turns to research. Rangers now find a different target if closestEnemy is too close.
=> Updated rockets and rangers

Player.java
Stopped producing mages and start checking for karbonite on round 5.
=> Minor Updates

Player.java
If there is a surplus of karbonite, we produce more factories. More factories means we have to slow production for each factory a bit more.
=> Updated factories

Player.java
Healers now stop trying to heal factories and do not go towards swarmLoc if there is someone to heal nearby
=> Updated Healers
